export const projects = [
  {
    title: "CodeCraft Summit",
    description: "A simple event subscriber with user ranking by links sent and AI assistance developed during NLW Connect event",
    image: "../../public/nlwConnect.png",
    tags: ["ReactJS", "Next.js", "NodeJS", "Google Gemini", "PostgresSQL", "Redis", "Prisma", "Fastify"],
    demo_url: "",
    github_url: "https://github.com/dhouglasbn/nlwConnect-ReactJS",
    color: "var(--neon-cyan)",
    featured: true,
  },
  {
    title: "Task",
    description: "A notion.so clone that allows users to make ToDo lists and allows teams to organize tasks",
    image: "https://i.ibb.co/GJ6zkCj/task1.png",
    tags: ["ReactJS", "NodeJS", "MongoDB", "TypeScript", "Express"],
    demo_url: "https://desafio-codex-grupo-3.github.io/desafio-codex-2024-FRONTEND/",
    github_url: "https://github.com/DESAFIO-CODEX-GRUPO-3/desafio-codex-2024-FRONTEND/tree/main",
    color: "var(--neon-pink)",
    featured: true,
  },
  {
    title: "Let Me Ask",
    description: "Q&A rooms App that allows people to get other users answers & AI answers developed during NLW Agents event",
    image: "../../public/nlwAgents.png",
    tags: ["ReactJS", "NodeJS", "Google Gemini", "Drizzle", "Fastify", "Tailwind", "Tanstack", "RadixUI"],
    demo_url: "#",
    github_url: "https://github.com/dhouglasbn/nlw-agents",
    color: "var(--neon-green)",
    featured: false,
  },
  {
    title: "JSExperts Drive",
    description: "A Google Drive Clone that uses pipeline and thread process to upload files developed during JSExperts event",
    image: "../../public/JSExperts5.png",
    tags: ["NodeJS", "Socket.io", "HTML5", "CSS3"],
    demo_url: "#",
    github_url: "https://github.com/dhouglasbn/jsExperts5",
    color: "var(--neon-cyan)",
    featured: false,
  },
  {
    title: "Pits A",
    description: "A server responsible for managing the whole business rules of a pizzaria",
    image: "../../public/pitsa.png",
    tags: ["SpringBoot", "JUnit5", "h2", "WebSockets"],
    demo_url: "#",
    github_url: "https://github.com/psoft-2023-1/projeto-psoft-grupo3-projeto-psoft",
    color: "var(--neon-pink)",
    featured: false,
  }
];